 #!/usr/bin/env python3
"""
Outlook Integration via PowerShell Scripts
Generates .ps1 scripts that create Outlook drafts with PDF attachments
"""

import os
from datetime import datetime

def generate_individual_email_script(customer_name, customer_email, company_name, 
                                     total_due, pdf_filename, statement_date=None):
    """
    Generate PowerShell script to create single Outlook draft
    
    Args:
        customer_name: Customer's name
        customer_email: Customer's email address
        company_name: Company name for email
        total_due: Total amount due (float)
        pdf_filename: Name of PDF file (will be in same folder as script)
        statement_date: Date for statement (defaults to today)
    
    Returns:
        str: PowerShell script content
    """
    if statement_date is None:
        statement_date = datetime.now().strftime('%B %d, %Y')
    
    # Email body template
    body = f"""Dear {customer_name},

Please find your account statement attached for your review.

Total Amount Due: ${total_due:,.2f}
Statement Date: {statement_date}

If you have any questions about your account, please don't hesitate to contact us.

Thank you for your business!

Best regards,
{company_name}"""

    subject = f"Account Statement from {company_name}"
    
    # Generate PowerShell script
    # Using heredoc for multi-line strings to avoid escaping issues
    script = f'''# Outlook Draft Creator - Generated by FSM System
# Customer: {customer_name}
# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Creating Outlook Draft for {customer_name}" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Get script directory
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$pdfPath = Join-Path $scriptDir "{pdf_filename}"

# Check if PDF exists
if (-not (Test-Path $pdfPath)) {{
    Write-Host "ERROR: PDF file not found!" -ForegroundColor Red
    Write-Host "Expected location: $pdfPath" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Please make sure the PDF is in the same folder as this script." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit
}}

Write-Host "✓ PDF found: {pdf_filename}" -ForegroundColor Green

try {{
    # Create Outlook application object
    Write-Host "✓ Connecting to Outlook..." -ForegroundColor Green
    $outlook = New-Object -ComObject Outlook.Application
    
    # Create new email
    $mail = $outlook.CreateItem(0)  # 0 = MailItem
    
    # Set properties
    $mail.To = "{customer_email}"
    $mail.Subject = "{subject}"
    $mail.Body = @"
{body}
"@
    
    # Attach PDF
    Write-Host "✓ Attaching PDF..." -ForegroundColor Green
    $mail.Attachments.Add($pdfPath)
    
    # Display draft (doesn't send, just opens for review)
    Write-Host "✓ Opening draft in Outlook..." -ForegroundColor Green
    $mail.Display()
    
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "SUCCESS! Draft created in Outlook" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Yellow
    Write-Host "1. Review the email in Outlook" -ForegroundColor White
    Write-Host "2. Make any changes if needed" -ForegroundColor White
    Write-Host "3. Click 'Send' when ready" -ForegroundColor White
    Write-Host ""
    Write-Host "The email will be saved to your Sent Items folder." -ForegroundColor White
    
}} catch {{
    Write-Host ""
    Write-Host "ERROR: Failed to create Outlook draft" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    Write-Host ""
    Write-Host "Troubleshooting:" -ForegroundColor Yellow
    Write-Host "- Make sure Outlook is installed" -ForegroundColor White
    Write-Host "- Try opening Outlook manually first" -ForegroundColor White
    Write-Host "- Close any Outlook error dialogs" -ForegroundColor White
    Read-Host "Press Enter to exit"
}}
'''
    
    return script


def generate_batch_email_script(customers_data, company_name, statement_date=None):
    """
    Generate PowerShell script to create multiple Outlook drafts
    
    Args:
        customers_data: List of dicts with keys: name, email, total_due, pdf_filename
        company_name: Company name
        statement_date: Date for statements (defaults to today)
    
    Returns:
        str: PowerShell script content
    """
    if statement_date is None:
        statement_date = datetime.now().strftime('%B %d, %Y')
    
    total_customers = len(customers_data)
    
    # Build customer array in PowerShell
    customer_array = "@(\n"
    for i, customer in enumerate(customers_data):
        customer_array += f'''    @{{
        Name = "{customer['name']}"
        Email = "{customer['email']}"
        TotalDue = {customer['total_due']:.2f}
        PDFFile = "{customer['pdf_filename']}"
    }}'''
        if i < total_customers - 1:
            customer_array += ","
        customer_array += "\n"
    customer_array += ")"
    
    script = f'''# Outlook Batch Draft Creator - Generated by FSM System
# Company: {company_name}
# Customers: {total_customers}
# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Batch Outlook Draft Creator" -ForegroundColor Cyan
Write-Host "{company_name}" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Get script directory
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Customer data
$customers = {customer_array}

Write-Host "Total customers: {total_customers}" -ForegroundColor White
Write-Host ""

# Show customer list
Write-Host "Recipients:" -ForegroundColor Yellow
foreach ($customer in $customers) {{
    Write-Host "  • $($customer.Name) <$($customer.Email)> - $($customer.TotalDue)" -ForegroundColor White
}}
Write-Host ""

# Confirmation
$confirm = Read-Host "Create $($customers.Count) drafts in Outlook? (Y/N)"
if ($confirm -ne "Y" -and $confirm -ne "y") {{
    Write-Host "Cancelled." -ForegroundColor Yellow
    exit
}}

Write-Host ""
Write-Host "Creating drafts..." -ForegroundColor Green

try {{
    # Connect to Outlook
    $outlook = New-Object -ComObject Outlook.Application
    
    $successCount = 0
    $errorCount = 0
    $errors = @()
    
    # Process each customer
    for ($i = 0; $i -lt $customers.Count; $i++) {{
        $customer = $customers[$i]
        $progress = $i + 1
        
        Write-Host "[$progress/{total_customers}] Processing $($customer.Name)..." -ForegroundColor Cyan
        
        try {{
            # Check PDF exists
            $pdfPath = Join-Path $scriptDir $customer.PDFFile
            if (-not (Test-Path $pdfPath)) {{
                throw "PDF file not found: $($customer.PDFFile)"
            }}
            
            # Create email
            $mail = $outlook.CreateItem(0)
            
            # Set properties
            $mail.To = $customer.Email
            $mail.Subject = "Account Statement from {company_name}"
            $mail.Body = @"
Dear $($customer.Name),

Please find your account statement attached for your review.

Total Amount Due: $($customer.TotalDue)
Statement Date: {statement_date}

If you have any questions about your account, please don't hesitate to contact us.

Thank you for your business!

Best regards,
{company_name}
"@
            
            # Attach PDF
            $mail.Attachments.Add($pdfPath)
            
            # Save to Drafts folder (doesn't display, doesn't send)
            $mail.Save()
            
            Write-Host "  ✓ Draft saved to Outlook Drafts folder" -ForegroundColor Green
            $successCount++
            
        }} catch {{
            Write-Host "  ✗ Error: $($_.Exception.Message)" -ForegroundColor Red
            $errorCount++
            $errors += @{{
                Customer = $customer.Name
                Error = $_.Exception.Message
            }}
        }}
    }}
    
    # Summary
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "Batch Process Complete!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "✓ Successfully created: $successCount drafts" -ForegroundColor Green
    
    if ($errorCount -gt 0) {{
        Write-Host "✗ Errors: $errorCount" -ForegroundColor Red
        Write-Host ""
        Write-Host "Error details:" -ForegroundColor Yellow
        foreach ($error in $errors) {{
            Write-Host "  • $($error.Customer): $($error.Error)" -ForegroundColor Red
        }}
    }}
    
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Yellow
    Write-Host "1. Open Outlook" -ForegroundColor White
    Write-Host "2. Go to Drafts folder" -ForegroundColor White
    Write-Host "3. Review each draft" -ForegroundColor White
    Write-Host "4. Click 'Send' on each email when ready" -ForegroundColor White
    Write-Host ""
    
    # Offer to open Drafts folder
    $openDrafts = Read-Host "Open Outlook Drafts folder now? (Y/N)"
    if ($openDrafts -eq "Y" -or $openDrafts -eq "y") {{
        try {{
            $namespace = $outlook.GetNamespace("MAPI")
            $draftsFolder = $namespace.GetDefaultFolder(16)  # 16 = Drafts
            $draftsFolder.Display()
        }} catch {{
            Write-Host "Could not open Drafts folder automatically. Please open Outlook manually." -ForegroundColor Yellow
        }}
    }}
    
}} catch {{
    Write-Host ""
    Write-Host "ERROR: Failed to process batch" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    Write-Host ""
    Write-Host "Troubleshooting:" -ForegroundColor Yellow
    Write-Host "- Make sure Outlook is installed" -ForegroundColor White
    Write-Host "- Try opening Outlook manually first" -ForegroundColor White
    Write-Host "- Close any Outlook error dialogs" -ForegroundColor White
}}

Write-Host ""
Read-Host "Press Enter to exit"
'''
    
    return script


def save_script_to_file(script_content, output_path):
    """
    Save PowerShell script to file with proper encoding
    
    Args:
        script_content: PowerShell script as string
        output_path: Where to save the .ps1 file
    
    Returns:
        str: Path to saved file
    """
    # Ensure .ps1 extension
    if not output_path.endswith('.ps1'):
        output_path += '.ps1'
    
    # Write with UTF-8 BOM for PowerShell compatibility
    with open(output_path, 'w', encoding='utf-8-sig') as f:
        f.write(script_content)
    
    return output_path


# Test function
if __name__ == "__main__":
    print("PowerShell Script Generator - Test Mode")
    print("=" * 50)
    
    # Test individual script
    print("\n1. Testing individual email script generation...")
    script = generate_individual_email_script(
        customer_name="John Smith",
        customer_email="john@example.com",
        company_name="Get a Grip Resurfacing",
        total_due=1234.56,
        pdf_filename="Statement_John_Smith_20260123.pdf"
    )
    
    output_file = save_script_to_file(script, "/tmp/test_individual_email.ps1")
    print(f"✓ Individual script saved: {output_file}")
    
    # Test batch script
    print("\n2. Testing batch email script generation...")
    customers = [
        {"name": "John Smith", "email": "john@example.com", "total_due": 1234.56, 
         "pdf_filename": "Statement_John_Smith.pdf"},
        {"name": "Jane Doe", "email": "jane@example.com", "total_due": 567.89,
         "pdf_filename": "Statement_Jane_Doe.pdf"},
        {"name": "Bob Johnson", "email": "bob@example.com", "total_due": 890.12,
         "pdf_filename": "Statement_Bob_Johnson.pdf"}
    ]
    
    script = generate_batch_email_script(
        customers_data=customers,
        company_name="Get a Grip Resurfacing"
    )
    
    output_file = save_script_to_file(script, "/tmp/test_batch_email.ps1")
    print(f"✓ Batch script saved: {output_file}")
    
    print("\n" + "=" * 50)
    print("✅ Test complete! Scripts generated in /tmp/")
    print("\nTo test on Windows:")
    print("1. Copy scripts and PDFs to same folder")
    print("2. Right-click .ps1 file → 'Run with PowerShell'")
