-- FieldKit Migration 030
-- Adds: work_order_attachments
-- Run on: all four databases (Get a Grip, Kleanit Charlotte, CTS, Kleanit South Florida)
-- Date: 2026-10-01
--
-- Why this exists:
--   Michele asked (2026-10-01) for the signed "occupied release" forms at Get
--   a Grip and CTS to live in the system instead of only in the office filing
--   cabinet: uploaded against the job they belong to, viewable from the work
--   order, and noted on the job description + the customer's invoice so
--   everyone can see a signed release exists for an occupied unit.
--
--   This is the app's FIRST inbound file upload. Everything the system did
--   with PDFs before this was outbound generation (invoices, statements,
--   reports, estimates) via reportlab -- nothing was ever accepted from a
--   user, so there was no attachment table, no upload route and no storage
--   location.
--
-- Design notes:
--   * Metadata only. The PDF bytes live on disk at
--     $UPLOAD_DIR/<company_key>/<stored_filename> (host folder bind-mounted
--     into the container, ./uploads -> /data/uploads in docker-compose.yml),
--     NOT in the database. Chris chose host-folder storage over BYTEA on
--     2026-10-01 so the signed forms stay browsable/copyable with ordinary
--     file tools; the per-company subfolder mirrors the one-DB-per-company
--     isolation rather than pooling four companies' documents together.
--   * `stored_filename` is always generated by the app (wo<id>_<random>.pdf),
--     never the user's own filename -- the uploaded name is kept separately
--     in `original_filename` purely for display and for the download name.
--     Serving a path built from a user-supplied filename is the classic
--     traversal hole; keeping the two columns separate makes that structural
--     rather than a thing each route has to remember.
--   * attachment_type exists so this table isn't single-purpose. Today the
--     only value written is 'occupied_release'; a future "before/after
--     photos" or "signed estimate" feature adds a value instead of a table.
--   * Soft delete per CLAUDE.md's blanket rule, and here it genuinely
--     matters: removing a signed liability release should never destroy the
--     record that one existed. The row is marked deleted_at and the file is
--     deliberately LEFT ON DISK -- recoverable, and the audit trail
--     (record_audit, migration 027) keeps who/when.
--   * No FK from work_order_id despite pointing at a real table in the same
--     DB? No -- a FK IS appropriate here (unlike the sales_* polymorphic
--     property_id columns, this only ever points at work_orders), so it gets
--     one, matching work_order_techs/work_order_status_history.

CREATE TABLE IF NOT EXISTS work_order_attachments (
    id                SERIAL PRIMARY KEY,
    work_order_id     INTEGER NOT NULL REFERENCES work_orders(id),
    attachment_type   VARCHAR(40) NOT NULL DEFAULT 'occupied_release',

    original_filename VARCHAR(255) NOT NULL,
    stored_filename   VARCHAR(255) NOT NULL,
    content_type      VARCHAR(100),
    byte_size         INTEGER,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    deleted_at TIMESTAMP NULL,
    deleted_by VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_wo_attachments_wo
    ON work_order_attachments(work_order_id, attachment_type) WHERE deleted_at IS NULL;
